name: main

on:
  push:
    branches: [ main ]

jobs:
  #  build:
  #    runs-on: ubuntu-22.04
  #
  #    strategy:
  #      matrix:
  #        node-version: [ 22.x ]
  #
  #    steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v4
  #
  #      - name: Corepack enable
  #        run: corepack enable
  #
  #      - name: Set up Node.js ${{ matrix.node-version }}
  #        uses: actions/setup-node@v4
  #        with:
  #          cache: 'yarn'
  #          node-version: ${{ matrix.node-version }}
  #
  #      - name: Install dependencies
  #        run: yarn
  #
  #      - name: Run build
  #        run: yarn build

  deploy:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [ 21.x ]

    #    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Corepack enable
        run: corepack enable

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn

      - name: Run build
        run: yarn build

#      - name: Publish to npm
#        uses: actions/upload-artifact@v4
#        with:
#          name: npm-package
#          path: dist/

      - name: Create npm Release
        run:
          npm publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
